project:
  type: website
  render:
  - "index.qmd"
  - "expected_points.qmd"
  - "predicting_games.qmd"
  - "estimating_efficiency.qmd"
  - "season_report.qmd"
  - "team_report.qmd"
  
format:
  html:
    author: "Phil Henrickson"
    date: today
    toc: true
    number-sections: true
    message: false
    warning: false
    code-fold: true
    code-overflow: scroll
    code-summary: 'Show the code'
    embed-resources: false
    html-math-method: mathjax
    fig-align: center
    theme: cerulean
    html-table-processing: none
    include-in-header:
    - text: |
          <style>
          .panel-tabset > .nav-tabs,
          .panel-tabset > .tab-content {border: none;}
          </style>
css: styles.css
